# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MicroserviceAgent_config = debug

else ifeq ($(config),release)
  MicroserviceAgent_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MicroserviceAgent

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MicroserviceAgent:
ifneq (,$(MicroserviceAgent_config))
	@echo "==== Building MicroserviceAgent ($(MicroserviceAgent_config)) ===="
	@${MAKE} --no-print-directory -C . -f MicroserviceAgent.make config=$(MicroserviceAgent_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MicroserviceAgent.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MicroserviceAgent"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"