package autogenerated;

import de.uniks.vs.jalica.engine.BasicBehaviour;

public abstract class DomainBehaviour extends BasicBehaviour {

    public DomainBehaviour(String name) {
        super(name);
    }

}
