package autogenerated;

import de.uniks.vs.jalica.common.utils.CommonUtils;
import de.uniks.vs.jalica.engine.BasicConstraint;
import de.uniks.vs.jalica.engine.IConstraintCreator;

public class TestConstraintCreator implements IConstraintCreator {

    public TestConstraintCreator() { }

    public BasicConstraint createConstraint(long constraintConfId) {

        //switch(constraintConfId){
            //default:
                CommonUtils.aboutError("ConstraintCreator: Unknown constraint requested: " + constraintConfId );
                return null;
            //   break;
    }
 }

