package autogenerated;

import de.uniks.vs.jalica.common.utils.CommonUtils;
import de.uniks.vs.jalica.engine.BasicCondition;
import de.uniks.vs.jalica.engine.IConditionCreator;


public class TestConditionCreator implements IConditionCreator {

    public TestConditionCreator() { }

    public BasicCondition createConditions(long conditionConfId) {

      //switch (conditionConfId)
      //{
        //case 1558109687647:
        if (conditionConfId == 1558109687647l) {
            return new TransitionCondition1558109687647();
            //return new PreCondition1558109687647>();
            //break;
        }
        //default:
        CommonUtils.aboutError("ConditionCreator: Unknown condition requested: " + conditionConfId);
        return null;
        //       break;
        //}
    }
}

