package autogenerated;

import de.uniks.vs.jalica.common.utils.CommonUtils;
import de.uniks.vs.jalica.engine.BasicUtilityFunction;
import de.uniks.vs.jalica.engine.IUtilityCreator;

public class TestUtilityFunctionCreator implements IUtilityCreator {

    public TestUtilityFunctionCreator() { }

    public BasicUtilityFunction createUtility(long utilityfunctionConfId) {

        //switch(utilityfunctionConfId)
        //{
            //case 1560257414138:
             if (utilityfunctionConfId == 1560257414138l)
                return new UtilityFunction1560257414138();
           //   break;
            //case 1560260998173:
             if (utilityfunctionConfId == 1560260998173l)
                return new UtilityFunction1560260998173();
           //   break;
            //case 1560261009408:
             if (utilityfunctionConfId == 1560261009408l)
                return new UtilityFunction1560261009408();
           //   break;
            //case 1560261023006:
             if (utilityfunctionConfId == 1560261023006l)
                return new UtilityFunction1560261023006();
           //   break;
            //case 1560261035058:
             if (utilityfunctionConfId == 1560261035058l)
                return new UtilityFunction1560261035058();
           //   break;
            //case 1560262020541:
             if (utilityfunctionConfId == 1560262020541l)
                return new UtilityFunction1560262020541();
           //   break;
            //default:
            else {
                CommonUtils.aboutError("UtilityFunctionCreator: Unknown utility requested: " + utilityfunctionConfId);
                return null;
            }
        //    break;
        //}
        //return null;
    }
}
