package autogenerated;

import de.uniks.vs.jalica.common.utils.CommonUtils;
import de.uniks.vs.jalica.engine.BasicCondition;
import de.uniks.vs.jalica.engine.RunningPlan;
import de.uniks.vs.jalica.engine.model.AbstractPlan;
import de.uniks.vs.jalica.engine.model.Behaviour;
import de.uniks.vs.jalica.engine.model.BehaviourConfiguration;

public class TransitionCondition1558109687647 extends BasicCondition {

    @Override
    public boolean evaluate(RunningPlan runningPlan) {

        if (CommonUtils.TC_DEBUG_debug) System.out.print("T: TransitionCondition1558109687647 evaluate ");

        boolean result = true;

        for (AbstractPlan abstractPlan :runningPlan.getActiveState().getPlans()) {

            if (abstractPlan instanceof Behaviour){
                Behaviour behaviour = (Behaviour) abstractPlan;
                result &= behaviour.isFinished();
            }
        }

        if (CommonUtils.TC_DEBUG_debug) System.out.println(" Result: " + result);
        return result;
    }
}
