# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
INCLUDES += -Iinclude -I../alica_plans/pkvr/gen-src/include -I../pkvr_common/include -I../../alica/alica_engine/include -I../../alica/alica_solver_interface/include -I../../alica/alica_common_config/include -I../../alica-supplementary/alica_capnzero_proxy/include -I../../essentials/id_manager/include -I../../essentials/system_config/include -I../../essentials/fsystem/include -I../../essentials/event_handling/include -I../../capnzero/capnzero/include -I../../capnproto/c++/src -I../../libzmq/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
ALL_LDFLAGS += $(LDFLAGS) -pthread ../../alica/alica_engine/bin/Debug/libalica_engine.a ../../dynamic-role-assignment/bin/Debug/libdynamic_role_assignment.a ../../essentials/id_manager/bin/Debug/libid_manager.a ../../essentials/system_config/bin/Debug/libsystem_config.a ../../essentials/fsystem/bin/Debug/libfsystem.a ../../alica-supplementary/alica_capnzero_proxy/bin/Debug/libalica_capnzero_proxy.a ../../capnzero/capnzero/bin/Debug/libcapnzero.a ../../capnzero/id_capnzero/bin/Debug/libid_capnzero.a ../../libzmq/cmake-build/lib/libzmq.a ../../capnproto/c++/.libs/libcapnp.a ../../capnproto/c++/.libs/libkj.a ../../yaml-cpp/build/libyaml-cpp.a
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug)
TARGETDIR = bin/Debug
TARGET = $(TARGETDIR)/PKVRAgent
OBJDIR = obj/Debug
DEFINES += -DALICA_DEBUG_ENABLED -DDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -std=c++14

else ifeq ($(config),release)
TARGETDIR = bin/Release
TARGET = $(TARGETDIR)/PKVRAgent
OBJDIR = obj/Release
DEFINES += -DALICA_DEBUG_ENABLED -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++14

else
  $(error "invalid configuration $(config)")
endif

# Per File Configurations
# #############################################


# File sets
# #############################################

OBJECTS :=

OBJECTS += $(OBJDIR)/BehaviourCreator.o
OBJECTS += $(OBJDIR)/ConditionCreator.o
OBJECTS += $(OBJDIR)/ConstraintCreator.o
OBJECTS += $(OBJDIR)/DomainBehaviour.o
OBJECTS += $(OBJDIR)/DomainCondition.o
OBJECTS += $(OBJDIR)/DummyPlan1585849746246.o
OBJECTS += $(OBJDIR)/DummyPlan1585849746246Constraints.o
OBJECTS += $(OBJDIR)/EntryPlan1585215541605.o
OBJECTS += $(OBJDIR)/EntryPlan1585215541605Constraints.o
OBJECTS += $(OBJDIR)/Idle.o
OBJECTS += $(OBJDIR)/Idle1585901211194.o
OBJECTS += $(OBJDIR)/Idle1585901211194Constraints.o
OBJECTS += $(OBJDIR)/IdlePlan1585900095632.o
OBJECTS += $(OBJDIR)/IdlePlan1585900095632Constraints.o
OBJECTS += $(OBJDIR)/Init.o
OBJECTS += $(OBJDIR)/Init1585210187368.o
OBJECTS += $(OBJDIR)/Init1585210187368Constraints.o
OBJECTS += $(OBJDIR)/MasterPlan1574275889504.o
OBJECTS += $(OBJDIR)/MasterPlan1574275889504Constraints.o
OBJECTS += $(OBJDIR)/Play.o
OBJECTS += $(OBJDIR)/Play1575039923358.o
OBJECTS += $(OBJDIR)/Play1575039923358Constraints.o
OBJECTS += $(OBJDIR)/Player1585922801787.o
OBJECTS += $(OBJDIR)/Player1585922801787Constraints.o
OBJECTS += $(OBJDIR)/Register.o
OBJECTS += $(OBJDIR)/Register1575026296341.o
OBJECTS += $(OBJDIR)/Register1575026296341Constraints.o
OBJECTS += $(OBJDIR)/UtilityFunctionCreator.o
OBJECTS += $(OBJDIR)/WaitForStart.o
OBJECTS += $(OBJDIR)/WaitForStart1575039858266.o
OBJECTS += $(OBJDIR)/WaitForStart1575039858266Constraints.o
OBJECTS += $(OBJDIR)/agent.o
OBJECTS += $(OBJDIR)/communication.o
OBJECTS += $(OBJDIR)/movement.o
OBJECTS += $(OBJDIR)/pkvr_skill_module.o
OBJECTS += $(OBJDIR)/reasoner.o
OBJECTS += $(OBJDIR)/vision.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking PKVRAgent
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning PKVRAgent
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/BehaviourCreator.o: ../alica_plans/pkvr/gen-src/src/BehaviourCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConditionCreator.o: ../alica_plans/pkvr/gen-src/src/ConditionCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConstraintCreator.o: ../alica_plans/pkvr/gen-src/src/ConstraintCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DomainBehaviour.o: ../alica_plans/pkvr/gen-src/src/DomainBehaviour.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DomainCondition.o: ../alica_plans/pkvr/gen-src/src/DomainCondition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DummyPlan1585849746246.o: ../alica_plans/pkvr/gen-src/src/DummyPlan1585849746246.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EntryPlan1585215541605.o: ../alica_plans/pkvr/gen-src/src/EntryPlan1585215541605.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Idle.o: ../alica_plans/pkvr/gen-src/src/Idle.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Idle1585901211194.o: ../alica_plans/pkvr/gen-src/src/Idle1585901211194.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IdlePlan1585900095632.o: ../alica_plans/pkvr/gen-src/src/IdlePlan1585900095632.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Init.o: ../alica_plans/pkvr/gen-src/src/Init.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Init1585210187368.o: ../alica_plans/pkvr/gen-src/src/Init1585210187368.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MasterPlan1574275889504.o: ../alica_plans/pkvr/gen-src/src/MasterPlan1574275889504.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Play.o: ../alica_plans/pkvr/gen-src/src/Play.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Play1575039923358.o: ../alica_plans/pkvr/gen-src/src/Play1575039923358.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Player1585922801787.o: ../alica_plans/pkvr/gen-src/src/Player1585922801787.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Register.o: ../alica_plans/pkvr/gen-src/src/Register.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Register1575026296341.o: ../alica_plans/pkvr/gen-src/src/Register1575026296341.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/UtilityFunctionCreator.o: ../alica_plans/pkvr/gen-src/src/UtilityFunctionCreator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WaitForStart.o: ../alica_plans/pkvr/gen-src/src/WaitForStart.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WaitForStart1575039858266.o: ../alica_plans/pkvr/gen-src/src/WaitForStart1575039858266.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DummyPlan1585849746246Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/DummyPlan1585849746246Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EntryPlan1585215541605Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/EntryPlan1585215541605Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Idle1585901211194Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/Idle1585901211194Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IdlePlan1585900095632Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/IdlePlan1585900095632Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Init1585210187368Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/Init1585210187368Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MasterPlan1574275889504Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/MasterPlan1574275889504Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Play1575039923358Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/Play1575039923358Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Player1585922801787Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/Player1585922801787Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Register1575026296341Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/Register1575026296341Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WaitForStart1575039858266Constraints.o: ../alica_plans/pkvr/gen-src/src/constraints/WaitForStart1575039858266Constraints.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/agent.o: src/pkvr/agent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/movement.o: src/pkvr/modules/actuators/movement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/communication.o: src/pkvr/modules/communication/communication.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/pkvr_skill_module.o: src/pkvr/modules/pkvr_skill_module.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/reasoner.o: src/pkvr/modules/reasoning/reasoner.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/vision.o: src/pkvr/modules/vision/vision.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif