package autogenerated.interfaces;

import de.uniks.vs.jalica.autogenerated.DomainBehaviour;

public abstract class BehaviourInterface {

    protected DomainBehaviour behaviour;

    public BehaviourInterface(DomainBehaviour behaviour) {
        this.behaviour = behaviour;
    }

    public abstract void onConstructor();

    public abstract void onInitialiseParameters();

    public abstract void onRun(String msg);
}

