package autogenerated.behaviours.implementations;

import autogenerated.interfaces.BehaviourInterface;
import de.uniks.vs.jalica.autogenerated.DomainBehaviour;
import de.uniks.vs.jalica.common.utils.CommonUtils;

public class ProxyImpl extends BehaviourInterface {

    public ProxyImpl(DomainBehaviour behaviour) {
        super(behaviour);
    }

    @Override
    public void onConstructor() {

    }

    @Override
    public void onInitialiseParameters() {

    }

    @Override
    public void onRun(String msg) {

        if (this.behaviour.isFinished()) {
            return;
        }
        System.out.println("B: Behaviour " + this.behaviour.getName()+ " RUN");

        if (CommonUtils.B_DEBUG_debug) System.out.println("B: " +this.behaviour.getName() + " starts Behaviour " + this.behaviour.getName() + "   onRun(MSG:" + msg + ")");

        for (int i = 0; i < 60; i++) {
            System.out.println("B: " +this.behaviour.getName() + " LOOP");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        if (CommonUtils.B_DEBUG_debug)  System.out.println("B: " +this.behaviour.getName() + " finished Behaviour " + this.behaviour.getName() + "   onRun(MSG:" + msg + ")");
        this.behaviour.notifyLoopFinished();
        if (CommonUtils.B_DEBUG_debug) System.out.println("B: PROXY BEHAVIOUR FINISHED");
    }
}
