#include "constraints/DatabasePlan1560261035058Constraints.h"
/*PROTECTED REGION ID(ch1560261035058) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:DatabasePlan
    /*
    * Tasks:  
    *
    * States: 
    *
    * Vars: 
    */
    
    
}
