#include "constraints/InitPlan1560257414138Constraints.h"
/*PROTECTED REGION ID(ch1560257414138) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:InitPlan
    /*
    * Tasks:  
    * - EP:1560257602072 : init (1560257324591)
    *
    * States: 
    * - InitState (1560257595608)
    * - RuntimeState (1560260429771)
    *
    * Vars: 
    */
    
    
    // State: InitState
    // State: RuntimeState
}
