#include "constraints/ProxyPlan1560261023006Constraints.h"
/*PROTECTED REGION ID(ch1560261023006) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:ProxyPlan
    /*
    * Tasks:  
    * - EP:1560626142730 : route (1559058183279)
    *
    * States: 
    * - Proxy (1560626146037)
    *
    * Vars: 
    */
    
    
    // State: Proxy
}
