#include "constraints/RegistryPlan1560260998173Constraints.h"
/*PROTECTED REGION ID(ch1560260998173) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:RegistryPlan
    /*
    * Tasks:  
    * - EP:1560262336022 : manage (1559058172419)
    *
    * States: 
    * - Registry (1560262338497)
    *
    * Vars: 
    */
    
    
    // State: Registry
}
