#include "constraints/RuntimePlan1560262020541Constraints.h"
/*PROTECTED REGION ID(ch1560262020541) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:RuntimePlan
    /*
    * Tasks:  
    * - EP:1560262056450 : manage (1559058172419)
    * - EP:1560262105459 : provide (1559058199488)
    * - EP:1560626030216 : route (1559058183279)
    *
    * States: 
    * - RegistryState (1560262059669)
    * - ServiceState (1560262108766)
    * - ProxyState (1560626037188)
    *
    * Vars: 
    */
    
    
    // State: RegistryState
    // State: ServiceState
    // State: ProxyState
}
