#include "constraints/ServicePlan1560261009408Constraints.h"
/*PROTECTED REGION ID(ch1560261009408) ENABLED START*/
        //Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:ServicePlan
    /*
    * Tasks:  
    * - EP:1560262212790 : provide (1559058199488)
    *
    * States: 
    * - Service (1560262220997)
    *
    * Vars: 
    */
    
    
    // State: Service
}
