#include "ConditionCreator.h"
#include "InitPlan1560257414138.h"
#include "RegistryPlan1560260998173.h"
#include "ServicePlan1560261009408.h"
#include "ProxyPlan1560261023006.h"
#include "DatabasePlan1560261035058.h"
#include "RuntimePlan1560262020541.h"

using namespace alicaAutogenerated;
namespace alica
{

    ConditionCreator::ConditionCreator()
    {
    }
    ConditionCreator::~ConditionCreator()
    {
    }

    std::shared_ptr<BasicCondition> ConditionCreator::createConditions(int64_t conditionConfId)
    {
        switch (conditionConfId)
        {
            case 1558109687647:
            return std::make_shared<PreCondition1558109687647>();
                break;
            default:
            std::cerr << "ConditionCreator: Unknown condition id requested: " << conditionConfId << std::endl;
            throw new std::exception();
            break;
        }
    }
}
