#include "ConstraintCreator.h"

#include "constraints/InitPlan1560257414138Constraints.h"
#include "constraints/RegistryPlan1560260998173Constraints.h"
#include "constraints/ServicePlan1560261009408Constraints.h"
#include "constraints/ProxyPlan1560261023006Constraints.h"
#include "constraints/DatabasePlan1560261035058Constraints.h"
#include "constraints/RuntimePlan1560262020541Constraints.h"

#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

    ConstraintCreator::ConstraintCreator()
    {
    }

    ConstraintCreator::~ConstraintCreator()
    {
    }


    shared_ptr<BasicConstraint> ConstraintCreator::createConstraint(int64_t constraintConfId)
    {
        switch(constraintConfId)
        {
            default:
            std::cerr << "ConstraintCreator: Unknown constraint requested: " << constraintConfId << std::endl;
            throw new std::exception();
            break;
        }
    }


}
