#include "DatabasePlan1560261035058.h"
/*PROTECTED REGION ID(eph1560261035058) ENABLED START*/
//Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:DatabasePlan
    /* generated comment
    */
    shared_ptr<UtilityFunction> UtilityFunction1560261035058::getUtilityFunction(Plan* plan)
    {
       /*PROTECTED REGION ID(1560261035058) ENABLED START*/
       std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
       return defaultFunction;
        /*PROTECTED REGION END*/
    }
}
