#include "RegistryPlan1560260998173.h"
/*PROTECTED REGION ID(eph1560260998173) ENABLED START*/
//Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:RegistryPlan
    /* generated comment
        Task: manage  -> EntryPoint-ID: 1560262336022
    */
    shared_ptr<UtilityFunction> UtilityFunction1560260998173::getUtilityFunction(Plan* plan)
    {
       /*PROTECTED REGION ID(1560260998173) ENABLED START*/
       std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
       return defaultFunction;
        /*PROTECTED REGION END*/
    }
}
