#include "RuntimePlan1560262020541.h"
/*PROTECTED REGION ID(eph1560262020541) ENABLED START*/
//Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:RuntimePlan
    /* generated comment
        Task: manage  -> EntryPoint-ID: 1560262056450
        Task: provide  -> EntryPoint-ID: 1560262105459
        Task: route  -> EntryPoint-ID: 1560626030216
    */
    shared_ptr<UtilityFunction> UtilityFunction1560262020541::getUtilityFunction(Plan* plan)
    {
       /*PROTECTED REGION ID(1560262020541) ENABLED START*/
       std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
       return defaultFunction;
        /*PROTECTED REGION END*/
    }
}
