#include "ServicePlan1560261009408.h"
/*PROTECTED REGION ID(eph1560261009408) ENABLED START*/
//Add additional options here
/*PROTECTED REGION END*/

using namespace alica;

namespace alicaAutogenerated
{
    //Plan:ServicePlan
    /* generated comment
        Task: provide  -> EntryPoint-ID: 1560262212790
    */
    shared_ptr<UtilityFunction> UtilityFunction1560261009408::getUtilityFunction(Plan* plan)
    {
       /*PROTECTED REGION ID(1560261009408) ENABLED START*/
       std::shared_ptr<UtilityFunction> defaultFunction = std::make_shared<DefaultUtilityFunction>(plan);
       return defaultFunction;
        /*PROTECTED REGION END*/
    }
}
