#include "UtilityFunctionCreator.h"
#include "InitPlan1560257414138.h"
#include "RegistryPlan1560260998173.h"
#include "ServicePlan1560261009408.h"
#include "ProxyPlan1560261023006.h"
#include "DatabasePlan1560261035058.h"
#include "RuntimePlan1560262020541.h"
#include <iostream>

using namespace alicaAutogenerated;

namespace alica
{

    UtilityFunctionCreator::~UtilityFunctionCreator()
    {
    }

    UtilityFunctionCreator::UtilityFunctionCreator()
    {
    }


    std::shared_ptr<BasicUtilityFunction> UtilityFunctionCreator::createUtility(int64_t utilityfunctionConfId)
    {
        switch(utilityfunctionConfId)
        {
            case 1560257414138:
                return std::make_shared<UtilityFunction1560257414138>();
                break;
            case 1560260998173:
                return std::make_shared<UtilityFunction1560260998173>();
                break;
            case 1560261009408:
                return std::make_shared<UtilityFunction1560261009408>();
                break;
            case 1560261023006:
                return std::make_shared<UtilityFunction1560261023006>();
                break;
            case 1560261035058:
                return std::make_shared<UtilityFunction1560261035058>();
                break;
            case 1560262020541:
                return std::make_shared<UtilityFunction1560262020541>();
                break;
            default:
            std::cerr << "UtilityFunctionCreator: Unknown utility requested: " << utilityfunctionConfId << std::endl;
            throw new std::exception();
            break;
        }
    }


}
