#pragma once

#include <engine/BasicConstraint.h>
#include <memory>
#include <iostream>

using namespace alica;

namespace alica
{
    class ProblemDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */
