package autogenerated.behaviours;

import autogenerated.behaviours.implementations.ServiceImpl;
import de.uniks.vs.jalica.autogenerated.DomainBehaviour;
import de.uniks.vs.jalica.engine.AlicaEngine;
import autogenerated.interfaces.BehaviourInterface;

public class Service extends DomainBehaviour {

    private BehaviourInterface behaviourImpl;

    public Service(AlicaEngine ae) {
        super("Service", ae);
        behaviourImpl = new ServiceImpl(this);
        behaviourImpl.onConstructor();
    }

    @Override
    public void run(Object msg) {
        behaviourImpl.onRun((String) msg);
    }

    @Override
    protected void initialiseParameters() {
        behaviourImpl.onInitialiseParameters();
    }

    @Override
    public void run() {

    }
}
